### ISSUE TITLE
Switching between questions not optimal on mobile

### ISSUE THREAD

**Issue by BryanChiu** [Python-Practice-Engine/src#102]
Severity: Low

OS: Windows 10 Home
Browser: Chrome 89.0.4389.82 (using device toolbar)

Description: On mobile, when switching questions, it stays at the bottom of the page with the code window, when it should scroll back up and present the user with the question text. Also, perhaps having the navigation buttons near the top allows the user to skip questions easier, without scrolling down below the code window.

**Comment by connorhewick** [comment]
Not intended for use on mobile.
