### ISSUE TITLE
The system hangs after running `node server.js`

### ISSUE THREAD

**Issue by leon1213** [Python-Practice-Engine/src#103]
![image](https://user-images.githubusercontent.com/48035126/110309578-7c7ea600-803c-11eb-934d-b30dad4c841e.png)
After running step 7 in `README.md`, the system hangs.
 
![image](https://user-images.githubusercontent.com/48035126/110309687-9ddf9200-803c-11eb-9799-821bf48e6af1.png)

**Comment by connorhewick** [comment]
the system isn't hanging. the terminal is running the backend service as intended (on port 3001)
