### ISSUE TITLE
Failure to Compile

### ISSUE THREAD

**Issue by Skeli789** [Python-Practice-Engine/src#48]
--Edit: Had I continued reading the README when the issue happened, I would have noticed you included this at the bottom. Either way, I'll leave this open so no one else reports it.

**Severity**: Critical

**Environment**: Windows 10 64-Bit, Google Chrome

**Description**: After cloning the repo and following the instructed setup, I received this error:

![image](https://user-images.githubusercontent.com/17243618/109148147-d9708700-7733-11eb-931a-7ce81a92d62d.png)

It seems like a simple fix, as it probably heavily dependant on my environment.

The full command line output can be found in the attached file:
[Compilation Error.txt](https://github.com/Python-Practice-Engine/src/files/6042680/Compilation.Error.txt)

**Steps to Recreate**:
1. Follow the instructed steps in the readme to compile and run the application.
2. Don't adjust any of the files downloaded.

**Comment by noa-barsky** [comment]
Hi there,

This appears to be an issue with ESLint. This is good to note, but moving forwards the application will be hosted, so this issue should not appear. See more information here: https://stackoverflow.com/questions/37826449/expected-linebreaks-to-be-lf-but-found-crlf-linebreak-style
