### ISSUE TITLE
SUGGESTION: Change Colour of "print" Syntax Highlighting

### ISSUE THREAD

**Issue by Skeli789** [Python-Practice-Engine/src#49]
**Severity**: Medium

**Environment**: Windows 10 64-Bit, Google Chrome

**Description**: I can barely see the "print" keyword in my browser. A lighter colour would work much better for it.
--Edit: This applies to the "type" keyword as well.

![image](https://user-images.githubusercontent.com/17243618/109149455-94e5eb00-7735-11eb-8503-4b8d41a4269e.png)

**Steps to Recreate**:
1. Start the application.
2. Type ``print`` in the workspace.

**Comment by noa-barsky** [comment]
The theme of the text-editor has been changed to light mode upon request of the professor, so it now looks like this:
<img width="612" alt="Screen Shot 2021-03-23 at 10 59 30 PM" src="https://user-images.githubusercontent.com/35268728/112247974-8bb04700-8c2b-11eb-91f7-42d161548bc9.png">
