### ISSUE TITLE
Difficulty Arrows Aren't Centred

### ISSUE THREAD

**Issue by Skeli789** [Python-Practice-Engine/src#52]
**Severity**: Very Low

**Environment**: Windows 10 64-Bit, Google Chrome

**Description**: The arrows in the buttons used to change difficulty aren't centred within the button. They lean more towards the bottom half of the button than the top half.

![image](https://user-images.githubusercontent.com/17243618/109164506-881ec280-7748-11eb-87f0-d2c156386464.png)

**Steps to Recreate**:
1. Start the application.
2. Observe the difficulty arrows on the lower part of the screen.

**Comment by noa-barsky** [comment]
They are centred, they use the same component (screenshot below) and in the other screenshot you can see that they are centred 
<img width="417" alt="Screen Shot 2021-03-23 at 11 08 53 PM" src="https://user-images.githubusercontent.com/35268728/112248824-fe6df200-8c2c-11eb-9438-d0afde7c653a.png">
<img width="497" alt="Screen Shot 2021-03-23 at 11 10 49 PM" src="https://user-images.githubusercontent.com/35268728/112248831-029a0f80-8c2d-11eb-8fae-42e81c23d65f.png">

**Comment by Skeli789** [comment]
Even in the screenshot you just sent they're not centred vertically. If you take a look in paint, there are 88 pixels between the top of the arrow and the top of the button, but only 64 pixels between the bottom of the arrow and the bottom of the button.
![image](https://user-images.githubusercontent.com/17243618/112402753-77c81c00-8ce3-11eb-9d6c-e25e036fa0fe.png)
