### ISSUE TITLE
Set-up instructions could be more detailed, and maybe some screenshots would be helpful

### ISSUE THREAD

**Issue by lim147** [Python-Practice-Engine/src#55]
I ran into problems running `npm install` and the issue was caused by a low version of the `node`. If you meet the same issue, try run `node -v ` to find out the version of node  on your machine, If it's lower than "12.19.0", try using this command:

nvm install 12.19.0
nvm use 12.19.0
node -v 

to upgrade its version. Then run `npm install` and `npm start` tagain, it should now work fine.

Also, you need to make sure that you have `nvm` installed before running the above command lines.

**Comment by noa-barsky** [comment]
Hi there,

Since this project will be shipped as a site users will not have to set it up this way in the future. For this reason I will be closing this issue. Thank you!
