### ISSUE TITLE
The total number of "Difficulty" levels  is not specified

### ISSUE THREAD

**Issue by lim147** [Python-Practice-Engine/src#56]
How many difficulty levels are there in total? What's the rank of the current difficulty level? Is there any protection mechanism to prevent players switch to a level that is beyond the range as designed?

It could be better to have the number indicating the difficulty level labeled together with <, > button for difficulty.

<img width="523" alt="Screen Shot 2021-02-25 at 5 56 56 PM" src="https://user-images.githubusercontent.com/35234798/109230420-dc4e9480-7792-11eb-9978-f1102a84b5b3.png">

**Comment by afzalch** [comment]
The difficulty level actually is to allow a user to proceed with a new concept or question. There aren't any distinct difficulty levels actually. There is a protection mechanism to prevent users from switching to a concept which they are not ready to do.
