### ISSUE TITLE
The entered code is lost when switching back to the old difficulty level page from another page

### ISSUE THREAD

**Issue by lim147** [Python-Practice-Engine/src#58]
When the user first enters some code into one difficulty level page, and then he decides to check a question in another difficulty level. However, if he decides to go back and do the old question, he would notice that the code he entered previously was cleared, so he has to re-enter the same content again. It would be nice the info is cashed and won't be deleted if just the difficulty level pages are switching.

**Comment by connorhewick** [comment]
has been fixed while addressed issue of refreshing entire page on difficultly switch
