### ISSUE TITLE
Missing feedback for unsuccessful submit if the code does not have syntax error

### ISSUE THREAD

**Issue by lim147** [Python-Practice-Engine/src#60]
There is no feedback provided when trying to submit a code that is syntax-correct but does not pass the test. Better to prompt our a message saying something like "Almost there! Do you want to try one more time?"

Example: miss the question mark symbol in the text
<img width="1207" alt="Screen Shot 2021-02-25 at 6 25 33 PM" src="https://user-images.githubusercontent.com/35234798/109232798-dc509380-7796-11eb-9ded-f9577e1c7f63.png">

**Comment by noa-barsky** [comment]
This is a good suggestion, but out of scope for this project as that would require analyzing the user's code. This tool is intended to be used in the classroom, so user will have in-person/virtual support if they are stuck on a question.
