### ISSUE TITLE
double scrollbar on the bottom when line of code passes the width of IDE

### ISSUE THREAD

**Issue by enricoflorentino** [Python-Practice-Engine/src#63]
When typing a really long line of code on one singular line, it will go past the width of the IDE and display a double scroll bar.

**Environment**: Windows, Google Chrome

**Steps to Reproduce**
* Visit a proper url: `http://localhost:3000/#/IDE/1`
* on the first line of code in the IDE, type a sentence very long

![pythonlearning-2](https://user-images.githubusercontent.com/33015189/109249168-2b0d2600-77b5-11eb-9f23-78a5061ea841.png)

**Comment by afzalch** [comment]
This has since been addressed with the fact that word wrap now occurs if the line exceeds the width of the IDE
