### ISSUE TITLE
Uncaught SyntaxError: expected expression, got '<'

### ISSUE THREAD

**Issue by teemh** [Python-Practice-Engine/src#66]
Using Ubuntu VM with Firefox. Console found this:

![image](https://user-images.githubusercontent.com/59770668/109358372-a3292980-7851-11eb-9b99-60d75b2fbdcc.png)

Not sure what the cause is. There seems to be some information here that might help:

https://stackoverflow.com/questions/28894074/syntaxerror-expected-expression-got

**Comment by noa-barsky** [comment]
It is common to have console warnings in a web application, often they come from npm packages. This does not hinder the application's ability to run, so it will not be addressed at this time.
