### ISSUE TITLE
Some imports are allowed in the python code.

### ISSUE THREAD

**Issue by teemh** [Python-Practice-Engine/src#72]
It looks like Skulpt allows some imports to be added. Not sure if this would be a security concern or information leak. Might want to see if you can disable if possible.

![image](https://user-images.githubusercontent.com/59770668/109366828-687bbd00-7862-11eb-8791-5a5c98cc9bf8.png)

![image](https://user-images.githubusercontent.com/59770668/109366840-74677f00-7862-11eb-9e00-49aaa3f0c1b6.png)

**Comment by connorhewick** [comment]
such imports are libraries that come with the base version of python. since some basic libraries provide core programming concepts so purposed change is not currently under consideration
