### ISSUE TITLE
Back-end susceptible to SQL injection

### ISSUE THREAD

**Issue by SamCymbaluk** [Python-Practice-Engine/src#74]
Steps to reproduce:
* Start backend
* Run `curl "localhost:3001/questions/1%20OR%20True"`

Expected result:
* An error is returned

Actual result:
* All questions are returned, indicating that the SQL query was modified

The above example is a non destructive one, but it would be possible to damage the database while this vulnerability exists.

**Comment by SamCymbaluk** [comment]
This can also be demonstrated by going to `http://localhost:3000/#/IDE/1%20OR%20True`

**Comment by connorhewick** [comment]
close with commit 70fac60c3a0a1fef4d53ac111e59cfcc09668f38
