### ISSUE TITLE
NPM installation in front-end directory failed

### ISSUE THREAD

**Issue by sophiajwchoi** [Python-Practice-Engine/src#75]
## Expected Behavior
- npm packages successfully installed packages in ../front-end

## Actual Behavior
-  npm package installation failed with errors.
## Steps to Reproduce the Problem

  1.  cd ../front-end
  1. run npm install

[2021-03-03T22_11_22_308Z-debug.log](https://github.com/Python-Practice-Engine/src/files/6079515/2021-03-03T22_11_22_308Z-debug.log)
- Attached an error log and the error can be found at the end of the file.

## Specifications

  - Platform: window 10 64 bit

**Comment by noa-barsky** [comment]
Hi there,

It appears to be a versioning issue with regards to node. Moving forward we will be hosting the application, so these sort of issue should be resolved. Thank you!

**Comment by sophiajwchoi** [comment]
Please close this issue after the TAs finish marking for external testing.
