### ISSUE TITLE
Typo / ambiguity in first question message

### ISSUE THREAD

**Issue by Rubinstd** [Python-Practice-Engine/src#76]
### Severity
Low

### Environment
Windows 10 Desktop
Chrome

### Steps to reproduce:
Run the application
1. Run the back-end and front-end as instructed.
2. Navigate to the front-end (automatically redirected to the route '#/IDE/1'.

### Expected:
Users should be requested to write the code for the first question.

### Actual:
A typo in the question has the word 'could' instead of 'code'.

### Screenshot:
Typo just below the yellow "PrintStatement" marker:
![image](https://user-images.githubusercontent.com/35268731/110014550-ed4a5900-7cf0-11eb-9c50-eaf2a7b51a00.png)

### Notes:
Along with the typo, I found  a few other vague aspects of the first question. Under the assumption that the user is brand new to coding, I suggest adding the following to remove ambiguity:
1. The explanation does a great job of telling users to wrap the string in quotation marks. It might be nice to also explain that these quotation marks will not appear in the printed result.
2. When asking for a string to be printed like "Hello World", it may be good to explain that the quotation marks should not be part of the printed result.
3. The code box has a comment stating "# Your Code Here". A new programmer may not know what comments are and need an explanation. It's possible a new user may simply write their code on the comment line, and then be confused why it doesn't work.

**Comment by noa-barsky** [comment]
The your code here line is removed and the type o is removed
