### ISSUE TITLE
No limit to the number of lines in the code window

### ISSUE THREAD

**Issue by Rubinstd** [Python-Practice-Engine/src#77]
### Severity
Low

### Environment
Windows 10 Desktop
Chrome

### Steps to reproduce:
Run the application
1. Go to any question.
2. Add empty lines/lines of code repeatedly.
3. Try to run the code.

### Expected:
There should be a limit to the number of lines a user can create.

### Actual:
The code window has no limit to the number of lines and therefore a user can endlessly create them resulting in a few undesirable effects:
1. The website will begin to lag if users attempt to manipulate (ex. highlight, remove, add, etc.) large quantities of lines. This will also occur if the code is run or submitted.
2. The scrollbar for the code window becomes slow and difficult to use.
3. Occasionally the line counter in the code window will error out, causing lines to be hidden outside of scrollable view, overlapping, etc.

### Notes:
This is absolutely an edge case and one that is unlikely to come up. But it may be nice to limit the number of lines to a reasonable number if only to reduce the stress on the application in the event that a user attempts this.

**Comment by raziusyed** [comment]
Due to this application being used by first year's we don't want to put limitations on to how much code they can enter and also we we see this issue as being a rare case in general.
