### ISSUE TITLE
Confusing output section

### ISSUE THREAD

**Issue by Rubinstd** [Python-Practice-Engine/src#80]
### Severity
Medium/High

### Environment
Windows 10 Desktop
Chrome

### Steps to reproduce:
Run the application
1. Go to any question and write code with an output (ex. a print statement or an error)

### Expected:
The output section should be clearly outlined so that users understand its purpose.

### Actual:
The output section is just below the code window without any visible borders, labels, or explanations. 

### Screenshot:
Output section (no border):
![image](https://user-images.githubusercontent.com/35268731/110158032-e38b2900-7db6-11eb-9625-f5ae92353183.png)

Border appearing after clicking on output section:
![image](https://user-images.githubusercontent.com/35268731/110157999-d837fd80-7db6-11eb-96cc-e0c600420483.png)

### Notes:
The output section has a border after it is clicked on. To make this section more clear to users I recommend:
1. Have the border always active.
2. The output window is quite small making it difficult to navigate in the event of large error messages or many print statements. The entire webpage doesn't use most of my screen space. You might as well use more of it to be able to increase font sizes (accessibility), make bigger sections, etc.
2. Have a label explaining that the output should popup in that area on the screen.
3. In the questions (specifically the first one explaining print statements), explains that the printed message will appear in this section instead of just saying it's "on screen".
4. To really go the extra mile, many web coding environments offer helpful feedback on whether the code was run successfully or how long it took to run. This will give users valuable feedback on whether their code generally had major errors. Python can be confusing for new users sometimes as it can succeed and print out a statement but then error further on. It could be nice to give the users a marker of whether their code ran successfully regardless of if it passes tests (that way they know it may be more of a semantic issue rather than a syntactic one).

**Comment by noa-barsky** [comment]
Added a box and automatic scroll to the bottom of the page when a user hits run
<img width="621" alt="Screen Shot 2021-03-24 at 12 14 32 AM" src="https://user-images.githubusercontent.com/35268728/112253885-ea7abe00-8c35-11eb-8f37-cd84ab57d6a8.png">
