### ISSUE TITLE
Page resize causes submit button to move in between difficulty arrows and label

### ISSUE THREAD

**Issue by Rubinstd** [Python-Practice-Engine/src#81]
### Severity
Low

### Environment
Windows 10 Desktop
Chrome

### Steps to reproduce:
Run the application
1. Resize the window until the width is <= ~1200

### Expected:
The page should resize nicely without causing any confusing interface changes.

### Actual:
The page resizes nicely at very small widths (<= 760) but fails to properly resize at widths within the 761-1200 width range. The submit button moves in between the difficulty arrows and label making for a very confusing interface.

### Screenshot:
![image](https://user-images.githubusercontent.com/35268731/110175638-1e4d8b00-7dd0-11eb-8daf-95d159c67880.png)

**Comment by noa-barsky** [comment]
This has been address by making the page's width wider.
