### ISSUE TITLE
Test case numbering is confusing

### ISSUE THREAD

**Issue by Rubinstd** [Python-Practice-Engine/src#82]
### Severity
Low

### Environment
Windows 10 Desktop
Chrome

### Steps to reproduce:
Run the application
1. Go to any question and look at the test case number.

### Expected:
The first test case on each question should be "Test Case #1".

### Actual:
The test case numbers are equivalent to the question numbers. This comes with 2 possible issues:
1. Some users may get confused when looking at question 2 (or above) as there is only 1 test case, but it's called "Test Case #2". Where is "Test Case #1"?
2. Imagine a future scenario where a user is completing a more complex question that requires multiple test cases (ex. various edge-case tests). The numbering system will be completely thrown off. For example, if question 4 had 2 tests, they would be called "Test Case #4" and "Test Case #5". Now the test cases for question 5 must start with "Test Case #6" which means they no longer line up with the question number, nor do they explain how many test cases exist for the given question.

### Notes:
A more appropriate naming system may be:
1. Name the test cases "Test Case #1", "Test Case #2" for each question.
2. Name the test cases "Test Case #1.1", "Test Case #1.2", etc. Or some equivalent naming system.

**Comment by noa-barsky** [comment]
We feel the design makes sense to most users; however, we appreciate the feedback
