### ISSUE TITLE
Topic tags could use some clarification

### ISSUE THREAD

**Issue by Rubinstd** [Python-Practice-Engine/src#83]
### Severity
Low

### Environment
Windows 10 Desktop
Chrome

### Steps to reproduce:
Run the application
1. Choose any question and view the topic tags underneath the question name.

### Expected:
The user should understand the purpose of the topic tags, and all relevant tags should be present for the question.

### Actual:
The topic tags are not explained in any way and some questions are missing topic tags. 
I believe users could benefit from a label beside the topic tags that says "Topics:". Users who are just starting programming will not know what the topic tags mean and may be confused as to why they are present.
I also believe the purpose of the topic tag is to teach users that programming topics are interconnected. Each question shouldn't have a unique tag, but rather a group of tags (some new and some old) to tie old ideas in with new ones.
For example:
- Question 1 makes use of the topic tag "PrintStatement". This accurately sums up all the topics presented.
- Question 2 makes use of the topic tag "Variables". But the user is asked to use variables, followed by print statements. So adding the "PrintStatement" would more accurately summarize the question topics.
- Question 3 makes use of the topic tag "Numbers". Not only does the question also use print statements (and can have the "PrintStatement" tag), but you can further add other helpful tags. For example, if you add a tag "Types". In the future, if a question asks calculate the type of a string variable (thus the "Numbers" tag is no longer relevant). You can use the tag "Types" again, and although the user hasn't previously found the type of a string, they will extrapolate that the process must be quite similar to that of finding the type of a number.

### Notes:
Ultimately consider how the tags can be used not only as summaries of the question but also as ways to group programmatic thinking ideas. Using the tags well can really improve the user's ability to learn to approach new situations by using previous (but different) programming experiences. Ideally, this reduces the amount of line-by-line help the user will require as they will learn to assess situations from the big-picture like a programmer.

**Comment by noa-barsky** [comment]
This is a valid concern; however, our mentor for the project wants it to be a single page application and does not want a user to have access to all the topics at once. The point of the application is to slowly build on a new topics, so yes many questions will cover more than one topic, but the tag is supposed to represent the new topic presented. This application will be used in a classroom in conjunction with a professor's teachings, so that is where the new topic/tag will be explained further.
