### ISSUE TITLE
Crash website when building very large array

### ISSUE THREAD

**Issue by Rubinstd** [Python-Practice-Engine/src#84]
### Severity
Medium

### Environment
Windows 10 Desktop
Chrome

### Steps to reproduce:
Run the application
1. Run the following code (on any question):
```
x = [y for y in range(100000000)]
```
### Expected:
The program should terminate if it requires too much memory and the user should be notified that the program was unable to run due to this error.

### Actual:
The website will attempt to run the program freezing for some time and eventually crashing. When run locally this also consumes a considerable amount of resources.

### Screenshot:
Page becoming unresponsive after trying to run the code:
![image](https://user-images.githubusercontent.com/35268731/110178998-51464d80-7dd5-11eb-9d45-42becf59fc91.png)

Page crashing after some time.:
![image](https://user-images.githubusercontent.com/35268731/110178913-2bb94400-7dd5-11eb-92ee-a0eb002b25e7.png)

**Comment by connorhewick** [comment]
resource management is handled by a third party library and out of scope to implement for this project
