### ISSUE TITLE
Change default webpage title

### ISSUE THREAD

**Issue by Rubinstd** [Python-Practice-Engine/src#85]
### Severity
Low

### Environment
Windows 10 Desktop
Chrome

### Steps to reproduce:
Run the application
1. Go to any question and view the title (shown in the web page's tab text)

### Expected:
The webpage tab title should provide a concise and clear summary of the purpose of that page.

### Actual:
The webpage tab title is set to the default "React App", providing users with no information. 

### Screenshot:
![image](https://user-images.githubusercontent.com/35268731/110179446-15f84e80-7dd6-11eb-92f4-a2c7b1ad4c67.png)

### Notes:
It may be nice if the webpage tab title included some useful information about the specific page (ex. the question number) so that users can have multiple questions open in various tabs and navigate these tabs with ease.

**Comment by myrithok** [comment]
It is probably also worth noting that the icon is the default React icon.

**Comment by noa-barsky** [comment]
Added!
