### ISSUE TITLE
Add an explanation of difficulty vs question somewhere in the UI

### ISSUE THREAD

**Issue by Rubinstd** [Python-Practice-Engine/src#87]
### Severity
Low

### Environment
Windows 10 Desktop
Chrome

### Steps to reproduce:
Run the application
1. Navigate to any question and click the difficult arrow to move to another question.

### Expected:
The user should understand the difference between difficulty level and just a single question.

### Actual:
The documentation states that users should be "able to change the difficulty of the problem to an easier or more difficult problem on the same set of topics". 
Currently, each difficulty level has a vastly different question (and thus users can't complete multiple questions of the same difficulty level) which is understandably due to time constraints. 
However, there is no explanation on the UI that explains the difference between difficulty level and question number. When more questions are added (and with them, the ability to view the next question of the same difficulty as the last), users will require an explanation on this system.
For the time being, it just feels as though difficulty level = question number.

**Comment by noa-barsky** [comment]
As of right now the professor wants to keep the application as a single page. I will bring up to him the possibility of adding and explanation page.
