### ISSUE TITLE
No Indicator To Show That Data Retrieval Failed

### ISSUE THREAD

**Issue by trevorNgo** [Python-Practice-Engine/src#88]
Simulating event that the backend server is down or cannot be reached, the frontend client will not indicate to the user that "something went wrong". Instead, the page will remain half operational including navigation buttons to the next question. When clicking to add difficulty, the app will insert NaN into the route of the url as seen in addressbar.

![image](https://user-images.githubusercontent.com/23327878/110211836-6919e200-7e66-11eb-9ee2-b3e762ed6892.png)

Netflix pioneered an engineering practice called Chaos Engineering. They would purposely take down their own systems using "Chaos Monkey" daemon to see how resilient their systems would handle it.

Severity: Low
Repro:
Launch the client using react-scripts, and purposely leave the backend server offline.

**Comment by connorhewick** [comment]
404 page has been implemented
