### ISSUE TITLE
Difference between Run and Submit is unclear

### ISSUE THREAD

**Issue by myrithok** [Python-Practice-Engine/src#90]
**Description:** The exact functions of the **Run** and **Submit** buttons are not obvious to the user. Both buttons run the user's python code and print any results or errors to the output space. This makes it difficult to tell what these buttons are for, especially if the code is incorrect. 

![image](https://user-images.githubusercontent.com/32877366/110256342-6b636580-7f66-11eb-8cc7-bfb972aa9ba6.png)

**Severity:** Low

**OS:** Windows 10 Enterprise
**Browser:** Chrome 89.0.4389.82

**Suggested Fix:** Consider doing one of the following:
- Add instructions somewhere on the page to explain what each of these buttons does.
- Rename the **Submit** button to **Run & Submit**.
- Alter the **Submit** button to check test cases without producing output.

**Comment by noa-barsky** [comment]
We will implement a passed and failed tag to show up when the submit functionality is working
