### ISSUE TITLE
Submit button moves below difficulty arrows on mobile

### ISSUE THREAD

**Issue by myrithok** [Python-Practice-Engine/src#91]
**Description:** The **Submit** button moves to below the **Difficulty arrows** when the page is formatted for mobile:

![image](https://user-images.githubusercontent.com/32877366/110256641-f002b380-7f67-11eb-9a0d-ce0e53ae1346.png)

This applies to all mobile formats built into chrome's device toolbar except for the Surface Duo.

**Severity:** Low

**OS:** Windows 10 Enterprise
**Browser:** Chrome 89.0.4389.82

**Steps to Replicate:**
- Launch the webapp
- Open chrome's inspector
- Click on Toggle device toolbar
- Select any of the mobile phone presets
- Scroll down to the bottom of the page

**Comment by connorhewick** [comment]
Not intended for use on mobile.
