### ISSUE TITLE
Arrangement of Run, Submit, and Difficulty buttons unusual on certain mobile formats

### ISSUE THREAD

**Issue by myrithok** [Python-Practice-Engine/src#92]
**Description:** The **Submit** button, **Run** button, and **Difficulty arrows** rearrange strangely on certain mobile formats:

![image](https://user-images.githubusercontent.com/32877366/110256897-51775200-7f69-11eb-8887-8de61efb6320.png)

This seems to apply to:
- iPhone 5/SE
- Galaxy Fold

**Severity:** Low

**OS:** Windows 10 Enterprise
**Browser:** Chrome 89.0.4389.82

**Steps to Replicate:**
- Launch the webapp
- Open chrome's inspector
- Click on Toggle device toolbar
- Select iPhone 5/SE or Galaxy Fold from the device preset menu
- Scroll down to the bottom of the page

**Comment by connorhewick** [comment]
Not intended for use on mobile.
