### ISSUE TITLE
Test Case Passed feedback too subtle

### ISSUE THREAD

**Issue by myrithok** [Python-Practice-Engine/src#93]
**Description:** The feedback to the user when a test case is passed is fairly subtle, and is especially difficult to spot when the page is resized or formatted for mobile. In these cases, the test cases are listed above the python workspace:

![image](https://user-images.githubusercontent.com/32877366/110257425-dbc0b580-7f6b-11eb-9d31-6a550b2e9c89.png)

This looks fine, and isn't a problem. But, when the user submits their test case by clicking the **Submit** button, they have to scroll all the way back up to the test cases to check whether or not their test cases passed:

![image](https://user-images.githubusercontent.com/32877366/110257473-1de9f700-7f6c-11eb-98e8-04ba0a3e5f10.png)

**Severity:** Low

**OS:** Windows 10 Enterprise
**Browser:** Chrome 89.0.4389.82

Suggested Fix: Consider adding some kind of feedback for passing test cases at the bottom of the page as well.

**Comment by connorhewick** [comment]
Not intended for use on mobile.
