### ISSUE TITLE
Consider formatting code snippets

### ISSUE THREAD

**Issue by myrithok** [Python-Practice-Engine/src#95]
**Description:** All 3 tutorials include code snippets. For example, *print()*, *print(2)*, and *print("Sally")* in the tutorial for question 1:

![image](https://user-images.githubusercontent.com/32877366/110258660-bafb5e80-7f71-11eb-9b97-b345862e52fb.png)

These code snippets may be confusing or difficult to distinguish from the surrounding English text; this is especially true for beginner programmers, who are the target audience of this webapp.

**Severity:** Low

**OS:** Windows 10 Enterprise
**Browser:** Chrome 89.0.4389.82

**Suggested Fix:** Consider adding some kind of markdown formatting to *clearly* differentiate English from code snippets in tutorial text.

**Comment by noa-barsky** [comment]
This is a really good idea, but it is out of scope for our current project.
