### ISSUE TITLE
Dockerize the application

### ISSUE THREAD

**Issue by Jailoodu** [Python-Practice-Engine/src#96]
**Summary**: Instead of having the user install Python and MySQL, dockerize the application so the environment is set up.

**Expected result**: No environment setup is required from the user to use this application. 

**Actual result**: User is required to install and set up Python and MySQL.

**Environment**: Microsoft Windows 10 Home.

**Severity**: Low.
**Priority**: Low.

**Comment by noa-barsky** [comment]
Hi there,

This is a great suggestion and if we were shipping this product not as a web app I think this would be the correct approach. However, the final version of this project is a web app, so users will be access it via a link. For this reason, we will not be dockerizing it.
