### ISSUE TITLE
Minor rewording required for sentence in question 1 tutorial

### ISSUE THREAD

**Issue by myrithok** [Python-Practice-Engine/src#97]
**Description:** The second-last sentence of the tutorial for question 1 reads "For example, print(“Sally”) the word Sally will be displayed."

![image](https://user-images.githubusercontent.com/32877366/110263687-711c7380-7f85-11eb-9fa3-1683ef624a1e.png)

This is a somewhat incoherent sentence. 

**Severity:** Low

**OS:** Windows 10 Enterprise
**Browser:** Chrome 89.0.4389.82

**Suggested Fix:** Reword this sentence. Perhaps "For example, running print("Sally") will display the word Sally."?

**Comment by noa-barsky** [comment]
<img width="577" alt="Screen Shot 2021-03-24 at 1 46 18 PM" src="https://user-images.githubusercontent.com/35268728/112359104-50ebf480-8ca7-11eb-96d2-844b72b2dfb9.png">
