### ISSUE TITLE
Console warnings on every page

### ISSUE THREAD

**Issue by myrithok** [Python-Practice-Engine/src#98]
**Description:** Loading the page for any question produces the following console warning:

![image](https://user-images.githubusercontent.com/32877366/110264745-002a8b00-7f88-11eb-91ef-bca3cad7c32e.png)

**Severity:** Low

**OS:** Windows 10 Enterprise
**Browser:** Chrome 89.0.4389.82

**Steps to Replicate:**
- Launch the webapp
- Open the browser's console
- Load any question page

**Comment by noa-barsky** [comment]
This a common among any web application. Unfortunately, it is necessary for development and not worth address at this time.
