### ISSUE TITLE
Long lines of code are cut off at the right edge

### ISSUE THREAD

**Issue by BryanChiu** [Python-Practice-Engine/src#99]
Severity: Medium

OS: Windows 10 Home
Browser: Chrome 89.0.4389.82

Description: A long line that requires horizontal scrolling cuts off the last few characters of the line.
![image](https://user-images.githubusercontent.com/25440765/110266051-ff472880-7f8a-11eb-904b-6aaba7072553.png)

**Comment by afzalch** [comment]
Word wrap is now being implemented for IDE, so this error no longer occurs.
